on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        type: choice
        options:
          - padavanonly/immortalwrt-mt798x
      device:
        description: device
        required: true
        type: choice
        options:
          - xiaomi_redmi-router-ax6000
      ref-version:
        description: ref version
        required: false
        default: ""
        type: string
      prefer-config:
        default: "mt7986-ax6000-mtwifi-cfg.config"

env:
  TZ: Asia/Shanghai
  WORKSPACE: /workspace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup env
        run: |
          sudo mkdir -p $WORKSPACE
          sudo chown $USER:$GROUPS $WORKSPACE
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

      - name: clone source
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ref_version='${{ inputs.ref-version }}'
          if [ "$ref_version" != "" ]; then
            ref_version="-b $ref_version"
          fi
          git clone --depth=1 $ref_version https://github.com/${{ inputs.repo }}.git openwrt

      - name: configure feeds
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: configure device
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          cp -f defconfig/${{ inputs.prefer-config }} .config
          echo 'CONFIG_SDK=y' >> .config
          echo 'CONFIG_MAKE_TOOLCHAIN=y' >> .config
          make defconfig
          cat .config

      - name: download package
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          make download -j$(nproc)

      - name: build toolchain
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make tools/install -j$(nproc) || make tools/install -j1 V=s
          make toolchain/install -j$(nproc) || make toolchain/install -j1 V=s

      - name: configure device
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          rm -rf .config
          cp -f defconfig/${{ inputs.prefer-config }} .config
          sed -Ei 's/(CONFIG_TARGET_MULTI_PROFILE)=y/\1=n/g' .config
          sed -Ei 's/(CONFIG_TARGET_DEVICE_mediatek.*)=y/\1=n/g' .config
          sed -Ei 's/(CONFIG_TARGET_DEVICE_mediatek_mt7986_DEVICE_${{ inputs.device }})=n/\1=y/g' .config
          echo 'CONFIG_IB=y' >> .config
          echo 'CONFIG_IB_STANDALONE=y' >> .config
          echo 'CONFIG_SDK=y' >> .config
          echo 'CONFIG_MAKE_TOOLCHAIN=y' >> .config
          # echo 'CONFIG_ALL_NONSHARED=y' >> .config
          # echo 'CONFIG_ALL_KMODS=y' >> .config
          # echo 'CONFIG_ALL=y' >> .config
          # sed -Ei 's/# (CONFIG_PACKAGE_.*?) is not set/\1=y/g' .config
          # echo 'CONFIG_TARGET_PROFILE="DEVICE_xiaomi_redmi-router-ax6000"' >> .config
          make defconfig
          cat .config

      - name: download package
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          make download -j$(nproc)

      - name: build
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt
          path: ${{ env.WORKSPACE }}/openwrt/bin/targets
