on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        type: choice
        options:
          - padavanonly/immortalwrt-mt798x
      device:
        description: device
        required: true
        type: choice
        options:
          - xiaomi_redmi-router-ax6000
      ref-version:
        description: ref version
        required: false
        default: ""
        type: string
      prefer-config:
        default: "mt7986-ax6000-mtwifi-cfg.config"

env:
  TZ: Asia/Shanghai
  WORKSPACE: /workspace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup env
        run: |
          sudo mkdir -p $WORKSPACE
          sudo chown $USER:$GROUPS $WORKSPACE
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

      - name: clone source
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ref_version='${{ inputs.ref-version }}'
          if [ "$ref_version" != "" ]; then
            ref_version="-b $ref_version"
          fi
          git clone --depth=1 $ref_version https://github.com/${{ inputs.repo }}.git openwrt

      - name: configure feeds
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: configure device (defconfig)
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          echo 'CONFIG_TARGET_mediatek=y' >> .config
          echo 'CONFIG_TARGET_mediatek_mt7986=y' >> .config
          echo 'CONFIG_MAKE_TOOLCHAIN=y' >> .config
          make defconfig
          cat .config

      # - name: download package
      #   working-directory: ${{ env.WORKSPACE }}/openwrt
      #   run: |
      #     make download -j$(nproc)
      #     find dl -size -1024c -exec ls -l {} \;
      #     find dl -size -1024c -exec rm -f {} \;
      #     make download -j$(nproc)

      - name: build
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make tools/install -j$(nproc) || make tools/install -j1 V=s
          make toolchain/install -j$(nproc) || make toolchain/install -j1 V=s

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt
          path: ${{ env.WORKSPACE }}/openwrt/bin/targets
