on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        type: choice
        options:
          - padavanonly/immortalwrt-mt798x
      ref-version:
        description: ref version
        required: false
        default: ""
        type: string
      prefer-config:
        default: "mt7986-ax6000-mtwifi-cfg.config"
        type: string

env:
  TZ: Asia/Shanghai
  WORKSPACE: /workspace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: ./.github/actions/setup-env

      - name: clone source
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ref_version='${{ inputs.ref-version }}'
          if [ "$ref_version" != "" ]; then
            ref_version="-b $ref_version"
          fi
          git clone --depth=1 $ref_version https://github.com/${{ inputs.repo }}.git openwrt

      - name: configure feeds
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: configure device
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          echo 'CONFIG_TARGET_mediatek=y' >> .config
          echo 'CONFIG_TARGET_mediatek_mt7986=y' >> .config
          make defconfig
          cat .config

      - name: build
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make tools/install -j$(nproc) || make tools/install -j1 V=s
          make toolchain/install -j$(nproc) || make toolchain/install -j1 V=s

      - name: compress
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          tar -czvf staging_dir.tar.gz staging_dir

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: toolchain
          path: |
            ${{ env.WORKSPACE }}/openwrt/staging_dir.tar.gz
