on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        type: choice
        options:
          - padavanonly/immortalwrt-mt798x
      device:
        description: device
        required: true
        type: choice
        options:
          - xiaomi_redmi-router-ax6000
      ref-version:
        description: ref version
        required: false
        default: ""
        type: string
      prefer-config:
        default: "mt7986-ax6000-mtwifi-cfg.config"
        type: string

env:
  TZ: Asia/Shanghai
  WORKSPACE: /workspace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: ./.github/actions/setup-env

      - name: clone source
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ref_version='${{ inputs.ref-version }}'
          if [ "$ref_version" != "" ]; then
            ref_version="-b $ref_version"
          fi
          git clone --depth=1 $ref_version https://github.com/${{ inputs.repo }}.git openwrt

      - name: configure feeds
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: configure device
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          cp -f defconfig/${{ inputs.prefer-config }} .config
          sed -i '/^CONFIG_TARGET_MULTI_PROFILE.*/d' .config
          sed -i '/^CONFIG_TARGET_DEVICE_.*/d' .config
          sed -i '/^CONFIG_TARGET_PER_DEVICE_ROOTFS.*/d' .config
          echo 'CONFIG_TARGET_mediatek_mt7986_DEVICE_${{ inputs.device }}=y' >> .config
          echo 'CONFIG_IB=y' >> .config
          echo 'CONFIG_IB_STANDALONE=y' >> .config
          make defconfig
          cat .config

      - name: build toolchain
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make tools/install -j$(nproc) || make tools/install -j1 V=s
          make toolchain/install -j$(nproc) || make toolchain/install -j1 V=s

      - name: download package
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          make download -j$(nproc)

      - name: build
        working-directory: ${{ env.WORKSPACE }}/openwrt
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt
          path: ${{ env.WORKSPACE }}/openwrt/bin/targets
